services:
  print-dech-db-server:
    image: 'mysql:lts'
    container_name: print-dech-db-server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: DechTech2.
      MYSQL_DATABASE: printer
      MYSQL_USER: printer
      MYSQL_PASSWORD: printer.20
    volumes:
      - print_dech_database:/var/lib/mysql
  print-dech:
    container_name: print-dech
    restart: always
    depends_on:
      - print-dech-db-server
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        ID_SERVER_DB_HOST: print-dech-db-server
        ID_SERVER_DB_PORT: 3306
    ports:
      - "8400:80"
volumes:
  print_dech_database:
